<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejemplo de Header y Footer</title>
    <link rel="stylesheet" href="apps/templades/styles.css">
</head>
<body>


    <footer>
        <div class="container">
            <p> 2024  Todos los derechos reservados.</p>
        </div>
    </footer>

</body>
</html>
