<?php require_once 'apps/templades/header.phtml'?>



       <?php if ($error):?>
            <div>
                <?= $error ?>
            </div>
        <?php endif ?>



    <form action="" method="post">

        <div>
            <label for="user">usuario</label>
            <input type="text" name="user" id="user" required>
        </div>

        <div>
            <label for="password">contraseña</label>
            <input type="password" name="password" id="password" required>

        </div>
            <button class="boton-ver-mas" type="submit">Login</button>

    </form>

<?php require_once 'apps/templades/footer.phtml'?>