<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <title></title>
    <link rel="stylesheet" href="apps/Css/styles.css">
    <link rel="stylesheet" type="text/css" href="apps/Css/caja.css">
</head>
<body>
<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
?>


    <header>
        <div class="container">
            <h1>Series</h1>
            <nav>
                <ul>
                    <li><a href="generos/ListaGeneros">Inicio</a></li>
                    <li><a href="series/ListaDeSeries">Series</a></li>
                    
                    
                    <?php if (isset($_SESSION['USER_USER'])): ?>
                        <li><a href="logout">Cerrar sesión</a></li>
                        <?php else: ?>
                        <li ><a href="login">Login</a></li>
                    <?php endif; ?>

                </ul>
            </nav>
        </div>
        <div>
            
        <?php if (isset($_SESSION['USER_USER'])): ?>
    <span>Usuario : <?= $_SESSION['USER_USER'] ?></span>
<?php endif; ?>

        </div>
    </header>

</body>
</html>
