<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejemplo de Header y Footer</title>
    <link rel="stylesheet" href="templades/styles.css">
</head>
<body>

    <header>
        <div class="container">
            <h1>series</h1>
            <nav>
                <ul>
                    <li><a href="router.php?action=generos/ListaGeneros">Inicio</a></li>
                    <li><a href="router.php?action=series/TodasLasSeries">Series</a></li>
                    
                </ul>
            </nav>
        </div>
    </header>

</body>