<head>
    <link rel="stylesheet" type="text/css" href="templades/caja.css">
</head>

<body>
    <div>
        <ul>
            <h1><?php echo $serie->nombre; ?></h1> 
            <li>Temporadas: <?php echo $serie->temporadas; ?></li> 
            <li>Protagonistas: <?php echo $serie->protagonistas; ?></li> 
            <li>Director: <?php echo $serie->director; ?></li> 
            <li>Calificación por Edad: <?php echo $serie->CalificacionPorEdad; ?></li> 
            <li>Resumen: <?php echo $serie->resumen; ?></li>
        </ul>
    </div>
</body>
