<head>
    <link rel="stylesheet" type="text/css" href="templades/caja.css">
</head>

<body>
    <div class="series-list">
        
        <?php foreach ($series as $i): ?>
            <div class="caja"> <!-- Cambié "caja.css" a "caja" -->
                <ul>
                    <h1><?php echo htmlspecialchars($i->nombre); ?></h1>
                    <li>Temporadas: <?php echo htmlspecialchars($i->temporadas); ?></li>
                    <li>Categoría:
                        <?php
                            
                            $nombreGenero = 'Desconocida';
                            foreach ($genero as $generos) {
                                if ($i->id_genero == $generos->id_genero) {
                                    $nombreGenero = $generos->genero; 
                                    break; 
                                }
                            }
                            echo htmlspecialchars($nombreGenero);
                        ?>
                    </li>
                    <button class="boton-ver-mas">
                        <a href="router.php?action=series/ver/<?php echo urlencode($i->nombre); ?>">Ver más</a>
                    </button>
                </ul>
            </div>
        <?php endforeach; ?>
    </div>
</body>
